/**
 * Created by zhangjinjin on 2019/4/11.
 */
export const ADD_COUNT = 'ADD_COUNT';
export const SOURCE_LIST = 'SOURCE_LIST';
export const CURRENT_BLOCK_KEY = 'CURRENT_BLOCK_KEY';
export const CURRENT_BLOCK_LIST = 'CURRENT_BLOCK_LIST';
export const  UPDATE_MENUACTIVENAME = 'UPDATE_MENUACTIVENAME';
export const  UPDATE_LESSIONS_STATUS = 'UPDATE_LESSIONS_STATUS';

